name: shrine
description: Learn how to use Material for structure and layout.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  geolocator: ^7.6.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2
  provider: ^6.0.5
  firebase_core: ^2.22.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  image_picker: ^1.0.4
  flutter_provider: ^2.1.0
  firebase_storage: ^11.0.15
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  lottie: ^2.7.0
  convex_bottom_bar: ^3.2.0
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: ^0.17.0
  url_launcher: ^6.1.14
  build_runner: ^2.4.6
  rive: ^0.12.3



flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/start_run.png
    - assets/start.png
    - assets/bear.json
    - assets/runner.png
    - assets/sweat.png
    - assets/cheetah.png
    - assets/dash_flutter_muscot.riv
    - assets/water-bar-demo.riv





    - assets/eagle.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600 # Use the correct weight value for Semi Bold
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf

