name: shrine
description: Discover how Material Components for Flutter make it easy to differentiate your product and express your brand through design.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2
  provider: ^6.0.0
  url_launcher: ^6.1.14
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/a.jpeg
    - assets/b.jpeg
    - assets/c.jpeg
    - assets/d.jpeg
    - assets/e.jpg
    - assets/f.jpg
    - assets/me1.json
